module.exports = {
  defaultServerResponse: {
    message: "",
    status: 400,
    body: [],
    errors: {},
  },
  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully!",
    CATEGORY_NOT_CREATED: "Category not Created!",
    CATEGORY_UPDATED: "Category Updated Successfully !",
    CATEGORY_NOT_UPDATED: "Category not Updated!",
    CATEGORY_DELETED: "Category Deleted Successfully!",
    CATEGORY_NOT_DELETED: "Category not Deleted!",
    CATEGORY_FETCHED: "Category Fetched Successfully!",
    PRODUCT_FETCHED: "Category Product fetched Successfully!",
    CATEGORY_NOT_FETCHED: "Category not Fetched!",
    CATEGORY_NOT_FOUND: "Category not Found!",
    CATEGORY_ERROR: "OOPS Error with Category!",
  },
  customerMessage: {
    CUSTOMER_CREATED: "Customer Register Successfully!",
    CUSTOMER_NOT_CREATED: "Customer Register Failed!",
    CUSTOMER_EXIST: "Customer Already Exists!",
    CUSTOMER_NOT_FETCHED: "Customer not Fetched!",
    CUSTOMER_NOT_DELETED: "Customer not Deleted",
    CUSTOMER_DELETED: "Customer Deleted!",
    ADDRESS_NOT_ADDED: "Address not Added!",
    ADDRESS_NOT_DELETE: "Address not Delete!",
    ADDRESS_NOT_UPDATED: "Address not Updated!",
    ADDRESS_NOT_FOUND: "Address not Found!",
    ADDRESS_ADDED: "Address Successfully Added!",
    ADDRESS_FETCHED: "Address Fetched!",
    ADDRESS_UPDATED: "Address Successfully Updated!",
    ADDRESS_DELETED: "Address Successfully Deleted!",
    CUSTOMER_FETCHED: "Customer Profile Fetched Successfully!",
    CUSTOMER_NOT_FOUND: "Account Not Found!",
    CUSTOMER_NOT_UPDATE: "Profile Not Found!",
    CUSTOMER_UPDATE: "Profile Updated Successfully!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    CUSTOMER_VERIFICATION_FAILED: "Account Verification Failed!",
    CUSTOMER_VERIFIED: "Account Verified!",
    OTP_SEND: "OTP Send to Your Email!",
    TRANSACTION_ADDED: "Transaction Added Successfully!",
    TRANSACTION_NOT_ADDED: "Transaction not Added!",
  },
  contactUsMessage: {
    CONTACTUS_CREATED: "Contact Us Created Successfully!",
    CONTACTUS_NOT_CREATED: "Contact Us not Created!",
    CONTACTUS_EXISTS: "Contact Us Exists Please Update it!",
    CONTACTUS_UPDATED: "Contact Us Updated Successfully !",
    CONTACTUS_NOT_UPDATED: "Contact Us not Updated!",
    CONTACTUS_DELETED: "Contact Us Deleted Successfully!",
    CONTACTUS_NOT_DELETED: "Contact Us not Deleted!",
    CONTACTUS_FETCHED: "Contact Us Fetched Successfully!",
    CONTACTUS_NOT_FETCHED: "Contact Us not Fetched!",
    CONTACTUS_NOT_FOUND: "Contact Us not Found!",
    CONTACTUS_ERROR: "OOPS Error with Contact Us!",
  },
  aboutUsMessage: {
    ABOUTUS_CREATED: "About Us Created Successfully!",
    ABOUTUS_NOT_CREATED: "About Us not Created!",
    ABOUTUS_EXISTS: "About Us Exists Please Update it!",
    ABOUTUS_UPDATED: "About Us Updated Successfully !",
    ABOUTUS_NOT_UPDATED: "About Us not Updated!",
    ABOUTUS_DELETED: "About Us Deleted Successfully!",
    ABOUTUS_NOT_DELETED: "About Us not Deleted!",
    ABOUTUS_FETCHED: "About Us Fetched Successfully!",
    ABOUTUS_NOT_FETCHED: "About Us not Fetched!",
    ABOUTUS_NOT_FOUND: "About Us not Found!",
    ABOUTUS_ERROR: "OOPS Error with About Us!",
  },
  experienceCentreMessage: {
    EXP_CENTRE_CREATED: "Experience Centre Created Successfully!",
    EXP_CENTRE_NOT_CREATED: "Experience Centre not Created!",
    EXP_CENTRE_EXISTS: "Experience Centre Exists Please Update it!",
    EXP_CENTRE_UPDATED: "Experience Centre Updated Successfully !",
    EXP_CENTRE_NOT_UPDATED: "Experience Centre not Updated!",
    EXP_CENTRE_DELETED: "Experience Centre Deleted Successfully!",
    EXP_CENTRE_NOT_DELETED: "Experience Centre not Deleted!",
    EXP_CENTRE_FETCHED: "Experience Centre Fetched Successfully!",
    EXP_CENTRE_NOT_FETCHED: "Experience Centre not Fetched!",
    EXP_CENTRE_NOT_FOUND: "Experience Centre not Found!",
    EXP_CENTRE_ERROR: "OOPS Error with Experience Centre!",
  },
  whyAwniMessage: {
    WHY_AWNI_CREATED: "Data Created Successfully!",
    WHY_AWNI_NOT_CREATED: "Data not Created!",
    WHY_AWNI_EXISTS: "Data Exists Please Update it!",
    WHY_AWNI_UPDATED: "Data Updated Successfully !",
    WHY_AWNI_NOT_UPDATED: "Data not Updated!",
    WHY_AWNI_DELETED: "Data Deleted Successfully!",
    WHY_AWNI_NOT_DELETED: "Data not Deleted!",
    WHY_AWNI_FETCHED: "Data Fetched Successfully!",
    WHY_AWNI_NOT_FETCHED: "Data not Fetched!",
    WHY_AWNI_NOT_FOUND: "Data not Found!",
    WHY_AWNI_ERROR: "OOPS Error with Data!",
  },
  wishlistMessage: {
    WISHLIST_CREATED: "Product added to Wishlist!",
    WISHLIST_NOT_CREATED: "Product not added to Wishlist !",
    WISHLIST_EXISTS: "Wishlist Exists Please Update it!",
    WISHLIST_UPDATED: "Wishlist Updated Successfully !",
    WISHLIST_NOT_UPDATED: "Wishlist not Updated!",
    WISHLIST_DELETED: "Product removed from wishlist!",
    WISHLIST_NOT_DELETED: "Wishlist not Deleted!",
    WISHLIST_FETCHED: "Wishlist Fetched Successfully!",
    WISHLIST_NOT_FETCHED: "Wishlist not Fetched!",
    WISHLIST_NOT_FOUND: "Wishlist not Found!",
    WISHLIST_ERROR: "OOPS Error with Wishlist!",
  },
  colorMessage: {
    COLOR_CREATED: "Color Created Successfully!",
    COLOR_NOT_CREATED: "Color not Created!",
    COLOR_EXISTS: "Color Exists Please Update it!",
    COLOR_UPDATED: "Color Updated Successfully !",
    COLOR_NOT_UPDATED: "Color not Updated!",
    COLOR_DELETED: "Color Deleted Successfully!",
    COLOR_NOT_DELETED: "Color not Deleted!",
    COLOR_FETCHED: "Color Fetched Successfully!",
    COLOR_NOT_FETCHED: "Color not Fetched!",
    COLOR_NOT_FOUND: "Color not Found!",
    COLOR_ERROR: "OOPS Error with Color!",
  },
  rangeMessage: {
    RANGE_CREATED: "Range Created Successfully!",
    RANGE_NOT_CREATED: "Range not Created!",
    RANGE_EXISTS: "Range Exists Please Update it!",
    RANGE_UPDATED: "Range Updated Successfully !",
    RANGE_NOT_UPDATED: "Range not Updated!",
    RANGE_DELETED: "Range Deleted Successfully!",
    RANGE_NOT_DELETED: "Range not Deleted!",
    RANGE_FETCHED: "Range Fetched Successfully!",
    RANGE_NOT_FETCHED: "Range not Fetched!",
    RANGE_NOT_FOUND: "Range not Found!",
    RANGE_ERROR: "OOPS Error with Range!",
  },
  enquiryMessage: {
    ENQUIRY_CREATED: "Enquiry Created Successfully!",
    ENQUIRY_NOT_CREATED: "Enquiry not Created!",
    ENQUIRY_EXISTS: "Enquiry Exists Please Update it!",
    ENQUIRY_UPDATED: "Enquiry Updated Successfully !",
    ENQUIRY_NOT_UPDATED: "Enquiry not Updated!",
    ENQUIRY_DELETED: "Enquiry Deleted Successfully!",
    ENQUIRY_NOT_DELETED: "Enquiry not Deleted!",
    ENQUIRY_FETCHED: "Enquiry Fetched Successfully!",
    ENQUIRY_NOT_FETCHED: "Enquiry not Fetched!",
    ENQUIRY_NOT_FOUND: "Enquiry not Found!",
    ENQUIRY_ERROR: "OOPS Error with Enquiry!",
  },
  franchiseeMessage: {
    FRANCHISEE_CREATED: "Franchisee Created Successfully!",
    FRANCHISEE_NOT_CREATED: "Franchisee not Created!",
    FRANCHISEE_EXISTS: "Franchisee Exists Please Update it!",
    FRANCHISEE_UPDATED: "Franchisee Updated Successfully !",
    FRANCHISEE_NOT_UPDATED: "Franchisee not Updated!",
    FRANCHISEE_DELETED: "Franchisee Deleted Successfully!",
    FRANCHISEE_NOT_DELETED: "Franchisee not Deleted!",
    FRANCHISEE_FETCHED: "Franchisee Fetched Successfully!",
    FRANCHISEE_NOT_FETCHED: "Franchisee not Fetched!",
    FRANCHISEE_NOT_FOUND: "Franchisee not Found!",
    FRANCHISEE_ERROR: "OOPS Error with Enquiry!",
  },
  sliderMessage: {
    SLIDER_CREATED: "Slider Created Successfully!",
    SLIDER_NOT_CREATED: "Slider not Created!",
    SLIDER_EXISTS: "Slider Exists Please Update it!",
    SLIDER_UPDATED: "Slider Updated Successfully !",
    SLIDER_NOT_UPDATED: "Slider not Updated!",
    SLIDER_DELETED: "Slider Deleted Successfully!",
    SLIDER_NOT_DELETED: "Slider not Deleted!",
    SLIDER_FETCHED: "Slider Fetched Successfully!",
    SLIDER_NOT_FETCHED: "Slider not Fetched!",
    SLIDER_NOT_FOUND: "Slider not Found!",
    SLIDER_ERROR: "OOPS Error with Slider!",
  },
  homepageBannerMessage: {
    HOMEPAGE_BANNER_CREATED: "Banner Created Successfully!",
    HOMEPAGE_BANNER_NOT_CREATED: "Banner not Created!",
    HOMEPAGE_BANNER_EXISTS: "Banner Exists Please Update it!",
    HOMEPAGE_BANNER_UPDATED: "Banner Updated Successfully !",
    HOMEPAGE_BANNER_NOT_UPDATED: "Banner not Updated!",
    HOMEPAGE_BANNER_DELETED: "Banner Deleted Successfully!",
    HOMEPAGE_BANNER_NOT_DELETED: "Banner not Deleted!",
    HOMEPAGE_BANNER_FETCHED: "Banner Fetched Successfully!",
    HOMEPAGE_BANNER_NOT_FETCHED: "Banner not Fetched!",
    HOMEPAGE_BANNER_NOT_FOUND: "Banner not Found!",
    HOMEPAGE_BANNER_ERROR: "OOPS Error with Banner!",
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created Successfully!",
    PRODUCT_NOT_CREATED: "Product not Created!",
    PRODUCT_UPDATED: "Product Updated Successfully !",
    PRODUCT_NOT_UPDATED: "Product not Updated!",
    PRODUCT_DELETED: "Product Deleted Successfully!",
    PRODUCT_NOT_DELETED: "Product not Deleted!",
    PRODUCT_FETCHED: "Product Fetched Successfully!",
    PRODUCT_NOT_FETCHED: "Product not Fetched!",
    PRODUCT_NOT_FOUND: "Product not Found!",
    PRODUCT_ERROR: "OOPS Error with Product!",
  },
  productImageMessage: {
    PRODUCT_IMG_CREATED: "Product Image Created Successfully!",
    PRODUCT_IMG_NOT_CREATED: "Product Image not Created!",
    PRODUCT_IMG_UPDATED: "Product Image Updated Successfully !",
    PRODUCT_IMG_NOT_UPDATED: "Product Image not Updated!",
    PRODUCT_IMG_DELETED: "Product Image Deleted Successfully!",
    PRODUCT_IMG_NOT_DELETED: "Product Image not Deleted!",
    PRODUCT_IMG_FETCHED: "Product Image Fetched Successfully!",
    PRODUCT_IMG_NOT_FETCHED: "Product Image not Fetched!",
    PRODUCT_IMG_NOT_FOUND: "Product Image not Found!",
    PRODUCT_IMG_ERROR: "OOPS Error with Product!",
  },
  productColorMessage: {
    PRODUCT_COLOR_CREATED: "Product Colour Created Successfully!",
    PRODUCT_COLOR_NOT_CREATED: "Product Colour not Created!",
    PRODUCT_COLOR_UPDATED: "Product Colour Updated Successfully !",
    PRODUCT_COLOR_NOT_UPDATED: "Product Colour not Updated!",
    PRODUCT_COLOR_DELETED: "Product Colour Deleted Successfully!",
    PRODUCT_COLOR_NOT_DELETED: "Product Colour not Deleted!",
    PRODUCT_COLOR_FETCHED: "Product Colour Fetched Successfully!",
    PRODUCT_COLOR_NOT_FETCHED: "Product Colour not Fetched!",
    PRODUCT_COLOR_NOT_FOUND: "Product Colour not Found!",
    PRODUCT_COLOR_ERROR: "OOPS Error with Product!",
  },
  adminMessage: {
    ADMIN_CREATED: "Admin Created Successfully!",
    ADMIN_PASSWORD_CREATED: "Password Created Successfully!",
    ADMIN_PASSWORD_NOT_CREATED: "Password Not Ctrated!",
    LOGIN_SUCCESS: "Successfully Logedin!",
    ADMIN_NOT_CREATED: "Admin not Created!",
    ADMIN_EXIST: "Admin Exists with this Email!",
    ADMIN_UPDATED: "Admin Updated Successfully !",
    ADMIN_NOT_UPDATED: "Admin not Updated!",
    ADMIN_DELETED: "Admin Deleted Successfully!",
    ADMIN_NOT_DELETED: "Admin not Deleted!",
    ADMIN_FETCHED: "Admin Fetched Successfully!",
    ADMIN_NOT_FETCHED: "Admin not Fetched!",
    ADMIN_NOT_FOUND: "Admin not Found!",
    ADMIN_ERROR: "OOPS Error with Admin!",
  },
  validationMessage: {
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Login First",
  },
  authMessage: {
    INVALID_PASSWORD: "Password is Invalid !",
    INVALID_EMAIL: "Invalid Email !",
    NEED_VERIFICATION: "Need Verification",
    NEED_LOGIN: "Need Login",
    LOGIN_SUCCESS: "Successfully LoggedIn !",
    ACCOUNT_DESABLED: "Account Disabled",
  },
};
